{
  "Header": {
    "Original": "CVE-2025-50817 (A vulnerability in the Python-Future 1.0.0 module allows for arbitrary ...)",
    "ID": "CVE-2025-50817",
    "Description": "(A vulnerability in the Python-Future 1.0.0 module allows for arbitrary ...)"
  },
  "Annotations": [
    {
      "Original": "- python-future \u003cremoved\u003e",
      "Type": "package",
      "Package": "python-future",
      "Kind": "removed"
    },
    {
      "Original": "[bookworm] - python-future \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "python-future",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://medium.com/@abcd_68700/cve-2025-50817-python-future-module-arbitrary-code-execution-via-unintended-import-of-test-py-f0818ea93cf4",
      "Type": "NOTE",
      "Description": "https://medium.com/@abcd_68700/cve-2025-50817-python-future-module-arbitrary-code-execution-via-unintended-import-of-test-py-f0818ea93cf4"
    },
    {
      "Original": "NOTE: https://github.com/PythonCharmers/python-future/issues/268",
      "Type": "NOTE",
      "Description": "https://github.com/PythonCharmers/python-future/issues/268"
    }
  ]
}