{
  "Header": {
    "Original": "CVE-2021-20285 (A flaw was found in upx canPack in p_lx_elf.cpp in UPX 3.96. This flaw ...)",
    "ID": "CVE-2021-20285",
    "Description": "(A flaw was found in upx canPack in p_lx_elf.cpp in UPX 3.96. This flaw ...)"
  },
  "Annotations": [
    {
      "Original": "- upx-ucl 4.2.2-1 (unimportant)",
      "Type": "package",
      "Package": "upx-ucl",
      "Kind": "fixed",
      "Version": "4.2.2-1",
      "Severity": "unimportant"
    },
    {
      "Original": "NOTE: https://github.com/upx/upx/issues/421",
      "Type": "NOTE",
      "Description": "https://github.com/upx/upx/issues/421"
    },
    {
      "Original": "NOTE: https://github.com/upx/upx/commit/13bc031163863cb3866aa6cdc018dff0697aa5d4 (v3.99)",
      "Type": "NOTE",
      "Description": "https://github.com/upx/upx/commit/13bc031163863cb3866aa6cdc018dff0697aa5d4 (v3.99)"
    }
  ]
}